### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by serra** [jkeuper/jkeuper.github.io#4]
https://michaelsoolee.com/google-analytics-jekyll/

I really regret doing this as late as last month.

**Comment by serra** [comment]
![image](https://user-images.githubusercontent.com/285398/30047801-4d492970-9213-11e7-8b39-54e34e5a9f4a.png)

**Comment by jkeuper** [comment]
Yeah, Google Analytics is awesome. I'm using it since 2006 on some other website. Unfortunately my websites are so simple, I'm not even close to unleashing the full power of Analytics...

You should really add some goals to your analytics. You can see how your website is doing for certain goals and even optimize your site for reaching goals. Goals might be destination pages, duration, # of pages/visit goals, external links, downloads, etc.

Read more about goals:
<https://blog.kissmetrics.com/critical-goal-types/>

Maybe you should add a goal for adding comments on your blog and lure people into adding comments, instead of disabling disqus? ;)
